// <auto-generated />
namespace ISofA.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Seat_Key_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seat_Key_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200659465_Seat_Key_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
